name: "admin_natural"

version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "default"

# Define file paths for different dbt components
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Define directories for compiled SQL files and clean targets
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configure models materialization
models:
  admin_natural:
    materialized: table # Change to "view" or "incremental" if needed
