default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 
      user: 
      password: ""
      role: ACCOUNTADMIN
      database: superstore_db
      warehouse: COMPUTE_WH # Change if needed
      schema: analytics
      threads: 6
      client_session_keep_alive: False
      query_tag: dbt-run
